version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_replica_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf.template
    env_file: .env
    command: sh -c "sed 's/{{REDIS_PASSWORD}}/${REDIS_PASSWORD}/' /usr/local/etc/redis/redis.conf.template > /usr/local/etc/redis/redis.conf && redis-server /usr/local/etc/redis/redis.conf --slaveof 179.43.176.207 6379 --masterauth \"${REDIS_PASSWORD}\""
    networks:
      - redis-network
    restart: always

networks:
  redis-network:
    driver: bridge

volumes:
  redis_replica_data: