version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf.template
    environment:
      - REDIS_ADDR=redis:6379
    env_file: .env
    command: sh -c "sed 's/{{REDIS_PASSWORD}}/${REDIS_PASSWORD}/' /usr/local/etc/redis/redis.conf.template > /usr/local/etc/redis/redis.conf && redis-server /usr/local/etc/redis/redis.conf"


  web:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile для Golang
    container_name: web
    environment:
      - REDIS_ADDR=redis:6379
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  alice:
    build:
      context: .
      dockerfile: Dockerfile.python  # Dockerfile для Python
    container_name: alice
    ports:
      - "2112:2112"
    depends_on:
      - redis
      - web

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  redis_data:
