FROM python:3.11-slim

WORKDIR /app

COPY services/telegram-bot/requirements_bot.txt .
RUN pip install --no-cache-dir -r requirements_bot.txt

COPY services/telegram-bot/telegram_bot.py .
COPY .env .

CMD ["python", "telegram_bot.py"]